language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-lab7-ListOnPoint
  - make -j
  - cd ./bin/
  - ./test/LOP_test
notifications:
  email: false
